# Generated by Django 4.2.4 on 2024-01-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('services', models.TextField()),
                ('orientation', models.CharField(max_length=250)),
                ('charges', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/images')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.area')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/gallery')),
                ('escort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.escort')),
            ],
        ),
    ]
